# Generated by Django 4.1.13 on 2024-05-28 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('frontal_page', models.ImageField(blank=True, null=True, upload_to='frontal_pages')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.book')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedBook',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('book_file', models.FileField(blank=True, null=True, upload_to='extracted_books')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_books', to='app.book')),
            ],
        ),
    ]
