# Generated by Django 4.1.13 on 2024-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bookmark_id_bookmark_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
