# Generated by Django 4.1.13 on 2024-09-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bindingitem_resource_type_alter_bindingitem_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindingitem',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('youtubevideo', 'YouTube Video'), ('notes', 'Notes'), ('web', 'Web')], default='web', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance'), ('mystery', 'Mystery'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('non_fiction', 'Non-Fiction'), ('biography', 'Biography'), ('self_help', 'Self-Help'), ('history', 'History'), ('horror', 'Horror'), ('adventure', 'Adventure'), ('young_adult', 'Young Adult'), ('children', 'Children’s Books'), ('cookbooks', 'Cookbooks'), ('travel', 'Travel'), ('science_nature', 'Science & Nature'), ('spiritual', 'Spiritual'), ('investing', 'Investing'), ('knowledge', 'Knowledge')], max_length=50),
        ),
    ]
