# Generated by Django 4.1.13 on 2024-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
