# Generated by Django 4.1.13 on 2024-08-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audiobook_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='audiobook_file',
            field=models.FileField(blank=True, null=True, upload_to='audiobooks/'),
        ),
    ]
