# Generated by Django 4.1.13 on 2024-08-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_audiobook_duration_book_audiobook_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='audiobook_file',
            new_name='audiobook',
        ),
    ]
