# Generated by Django 4.1.13 on 2024-08-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_audiobook_file_book_audiobook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='audiobook',
            new_name='audiobook_file',
        ),
    ]
